name: PR Security Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write
  id-token: write # allow the reusable workflow to mint an OIDC token for AWS

jobs:
  full-security:
    name: Full Security Gate
    uses: baks7101/SecureStack-platform/.github/workflows/full-security-scan.yml@main
    with:
      scan-path: "."
      has-docker: true
      has-terraform: true
      has-kubernetes: true
      run-dast: false
      has-ai: true
      aws-role-arn: arn:aws:iam::761584754677:role/github-actions-ai-vibecode-lab
    secrets: inherit